### ISSUE TITLE
那个能帮忙编译支持auth_chain_b

### ISSUE THREAD

**Issue by loveproe** [shadowsocksr-backup/shadowsocksr-android#1]

**Comment by manyang901** [comment]
release一个吧，签名不对没关系

**Comment by Balnea** [comment]
同求，想自己学编译一个APK，但是感觉还是不会。

**Comment by PolarBearsCN** [comment]
@Balnea 
[ShadowsocksR 协议插件文档](https://github.com/shadowsocksr-backup/shadowsocks-rss/blob/master/ssr.md)
>auth_chain_b（强烈推荐）：与auth_chain_a几乎一样，但TCP部分采用特定模式的数据包分布（模式由密码决定），使得看起来像一个实实在在的协议，使数据包分布分析和熵分析难以发挥作用。如果你感觉当前的模式可能被识别，那么你只要简单的更换密码就解决问题了。此协议为测试版本协议，不能兼容原协议。

**Comment by huihuimoe** [comment]
built

**Comment by ByownLau** [comment]
1





------------------ 原始邮件 ------------------
发件人: "Hui Hui";<notifications@github.com>;
发送时间: 2017年8月2日(星期三) 晚上7:59
收件人: "shadowsocksr-backup/shadowsocksr-android"<shadowsocksr-android@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [shadowsocksr-backup/shadowsocksr-android] 那个能帮忙编译支持auth_chain_b (#1)




Closed #1.
