### ISSUE TITLE
add auth_chain_b android客户端无法上网

### ISSUE THREAD

**Issue by liwei19920307** [shadowsocksr-backup/shadowsocksr-android#2]
add auth_chain_b android客户端无法上网

**Comment by wangyu1314** [comment]
对。安卓4.4也不能运行auth_chain_b，拜托测试下。

**Comment by shadowxr** [comment]
auth_chain_b同出现断流问题，开网页经常性404
auth_chain_a无问题或影响较小，我没感觉
https://github.com/glzjin/ss-panel-v3-mod
魔改面板的节点

**Comment by shadowxr** [comment]
chain_a好像也会出现断流，因为出现频率远小于b的，不知道是我网络的问题还是
部分Logcat如下，不知道有没有用
手机回复，页面相关功能不能用，所以只能粘贴一长串
建议在软件内的相关加上github下载链接
GuardedProcess: start process: ArrayBuffer(/data/user/0/in.zhaoj.shadowsocksr/ss-local, -V, -x, -b, 127.0.0.1, -t, 600, --host, ***, -P, /data/user/0/in.zhaoj.shadowsocksr, -c, /data/user/0/in.zhaoj.shadowsocksr/ss-local-vpn.conf, --acl, /data/user/0/in.zhaoj.shadowsocksr/self.acl, --fast-open)
08-03 17:42:12.426 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:12.426 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:12.433 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:12.433 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:12.438 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:12.438 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:12.439 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:12.439 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:12.439 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:12.439 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:12.439 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:12.439 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:12.440 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:12.440 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:12.443 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:12.444 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:12.464 26088 26088 D shadowsocks: initializing acl...
08-03 17:42:12.581 26088 26088 D shadowsocks: protocol auth_chain_b
08-03 17:42:12.581 26088 26088 D shadowsocks: protocol_param
08-03 17:42:12.581 26088 26088 D shadowsocks: method none
08-03 17:42:12.581 26088 26088 D shadowsocks: obfs tls1.2_ticket_auth
08-03 17:42:12.581 26088 26088 D shadowsocks: obfs_param www.bing.com
08-03 17:42:12.581 26088 26088 D shadowsocks: using tcp fast open
08-03 17:42:12.581 26088 26088 D shadowsocks: initializing ciphers... none
08-03 17:42:13.460 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:13.460 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:13.464 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:13.464 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:13.467 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:13.467 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:13.469 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:13.469 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:13.475 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:13.475 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:13.481 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:13.482 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:13.927 26088 26088 D shadowsocks: tcp port reuse enabled
08-03 17:42:13.928 26088 26088 D shadowsocks: listening at 127.0.0.1:1080

**Comment by shadowxr** [comment]
chain_a好像也会出现断流，因为出现频率远小于b的，不知道是我网络的问题还是
部分Logcat如下，不知道有没有用
手机回复，页面相关功能不能用，所以只能粘贴一长串
建议在软件内的相关加上github下载链接

GuardedProcess: invalid address or address of corrupt block 0xab5fd350 passed to dlfree
08-03 17:42:12.315 26072 26072 F libc    : invalid address or address of corrupt block 0xab5fd350 passed to dlfree
08-03 17:42:12.316 26072 26072 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdeadbaad in tid 26072 (ss-local)
08-03 17:42:12.409 24777 24777 D tun2socks: ERROR(BConnection): recv failed
08-03 17:42:12.412 24696 24854 I GuardedProcess: start process:
GuardedProcess: start process: ArrayBuffer(/data/user/0/in.zhaoj.shadowsocksr/ss-local, -V, -x, -b, 127.0.0.1, -t, 600, --host, ***, -P, /data/user/0/in.zhaoj.shadowsocksr, -c, /data/user/0/in.zhaoj.shadowsocksr/ss-local-vpn.conf, --acl, /data/user/0/in.zhaoj.shadowsocksr/self.acl, --fast-open)
08-03 17:42:12.426 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:12.426 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:12.433 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:12.433 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:12.438 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:12.438 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:12.439 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:12.439 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:12.439 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:12.439 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:12.439 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:12.439 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:12.440 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:12.440 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:12.443 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:12.444 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:12.464 26088 26088 D shadowsocks: initializing acl...
08-03 17:42:12.581 26088 26088 D shadowsocks: protocol auth_chain_b
08-03 17:42:12.581 26088 26088 D shadowsocks: protocol_param
08-03 17:42:12.581 26088 26088 D shadowsocks: method none
08-03 17:42:12.581 26088 26088 D shadowsocks: obfs tls1.2_ticket_auth
08-03 17:42:12.581 26088 26088 D shadowsocks: obfs_param www.bing.com
08-03 17:42:12.581 26088 26088 D shadowsocks: using tcp fast open
08-03 17:42:12.581 26088 26088 D shadowsocks: initializing ciphers... none
08-03 17:42:13.460 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:13.460 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:13.464 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:13.464 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:13.467 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:13.467 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:13.469 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:13.469 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:13.475 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:13.475 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:13.481 24777 24777 D tun2socks: ERROR(BConnection): connection failed
08-03 17:42:13.482 24777 24777 D tun2socks: ERROR(BSocksClient): connection failed
08-03 17:42:13.927 26088 26088 D shadowsocks: tcp port reuse enabled
08-03 17:42:13.928 26088 26088 D shadowsocks: listening at 127.0.0.1:1080

**Comment by manyang901** [comment]
我也有这样的问题，
服务端log是
 checksum error ： （一大串码）
connection closed（） by peer （IPV6地址）

**Comment by JohnFreeman9** [comment]
维护者并没有合并正确的libev代码，出错是必然

**Comment by dna1982** [comment]
c#版本的客户端auth_chain_b是可以正常用的，说明server端的auth_chain_b也没问题。
八成是非官方那个Android客户端（3.4.0.7）的问题了。
