### ISSUE TITLE
how can i use kcptun with this client

### ISSUE THREAD

**Issue by zuozonglin** [shadowsocksr-backup/shadowsocksr-android#7]
how can i use kcptun with this client? dose it support ?or use kcptun plugin

**Comment by hdudhhhdh** [comment]
it seems that only the official shadowsocks client support this plugin,and this ssr client does not support kcptun either.

**Comment by zuozonglin** [comment]
thanks , but i see "Add KCP support" in the master branch ,what does it mean

**Comment by CKrome** [comment]
You can use this version of SSR which has a package name( net.htcp.shadowsocksr) version 3.4.2.2.
It has KCP support.

**Comment by zuozonglin** [comment]
@CKrome  Thanks

**Comment by jizusun** [comment]
Excuse me, where can I get a relaese of net.htcp.shadowsocksr version 3.4.2.2, thanks
